// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: proxy/satls/config.proto

package satls

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account binds a SATLS path token to a user.
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_satls_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_satls_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_satls_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ServerConfig carries the SATLS inbound users.
type ServerConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Users            []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	PathSalt         string                 `protobuf:"bytes,2,opt,name=path_salt,json=pathSalt,proto3" json:"path_salt,omitempty"`
	CertFile         string                 `protobuf:"bytes,3,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile          string                 `protobuf:"bytes,4,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	ServerName       string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	RejectUnknownSni bool                   `protobuf:"varint,6,opt,name=reject_unknown_sni,json=rejectUnknownSni,proto3" json:"reject_unknown_sni,omitempty"`
	UpServerName     string                 `protobuf:"bytes,7,opt,name=up_server_name,json=upServerName,proto3" json:"up_server_name,omitempty"`
	DownServerName   string                 `protobuf:"bytes,8,opt,name=down_server_name,json=downServerName,proto3" json:"down_server_name,omitempty"`
	UpCertFile       string                 `protobuf:"bytes,9,opt,name=up_cert_file,json=upCertFile,proto3" json:"up_cert_file,omitempty"`
	UpKeyFile        string                 `protobuf:"bytes,10,opt,name=up_key_file,json=upKeyFile,proto3" json:"up_key_file,omitempty"`
	DownCertFile     string                 `protobuf:"bytes,11,opt,name=down_cert_file,json=downCertFile,proto3" json:"down_cert_file,omitempty"`
	DownKeyFile      string                 `protobuf:"bytes,12,opt,name=down_key_file,json=downKeyFile,proto3" json:"down_key_file,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_satls_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_satls_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_satls_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetPathSalt() string {
	if x != nil {
		return x.PathSalt
	}
	return ""
}

func (x *ServerConfig) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *ServerConfig) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *ServerConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerConfig) GetRejectUnknownSni() bool {
	if x != nil {
		return x.RejectUnknownSni
	}
	return false
}

func (x *ServerConfig) GetUpServerName() string {
	if x != nil {
		return x.UpServerName
	}
	return ""
}

func (x *ServerConfig) GetDownServerName() string {
	if x != nil {
		return x.DownServerName
	}
	return ""
}

func (x *ServerConfig) GetUpCertFile() string {
	if x != nil {
		return x.UpCertFile
	}
	return ""
}

func (x *ServerConfig) GetUpKeyFile() string {
	if x != nil {
		return x.UpKeyFile
	}
	return ""
}

func (x *ServerConfig) GetDownCertFile() string {
	if x != nil {
		return x.DownCertFile
	}
	return ""
}

func (x *ServerConfig) GetDownKeyFile() string {
	if x != nil {
		return x.DownKeyFile
	}
	return ""
}

var File_proxy_satls_config_proto protoreflect.FileDescriptor

const file_proxy_satls_config_proto_rawDesc = "" +
	"\n" +
	"\x18proxy/satls/config.proto\x12\x12v2node.proxy.satls\x1a\x1acommon/protocol/user.proto\"\x1d\n" +
	"\aAccount\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xc0\x03\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x12\x1b\n" +
	"\tpath_salt\x18\x02 \x01(\tR\bpathSalt\x12\x1b\n" +
	"\tcert_file\x18\x03 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x04 \x01(\tR\akeyFile\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x12,\n" +
	"\x12reject_unknown_sni\x18\x06 \x01(\bR\x10rejectUnknownSni\x12$\n" +
	"\x0eup_server_name\x18\a \x01(\tR\fupServerName\x12(\n" +
	"\x10down_server_name\x18\b \x01(\tR\x0edownServerName\x12 \n" +
	"\fup_cert_file\x18\t \x01(\tR\n" +
	"upCertFile\x12\x1e\n" +
	"\vup_key_file\x18\n" +
	" \x01(\tR\tupKeyFile\x12$\n" +
	"\x0edown_cert_file\x18\v \x01(\tR\fdownCertFile\x12\"\n" +
	"\rdown_key_file\x18\f \x01(\tR\vdownKeyFileB'Z%github.com/wyx2685/v2node/proxy/satlsb\x06proto3"

var (
	file_proxy_satls_config_proto_rawDescOnce sync.Once
	file_proxy_satls_config_proto_rawDescData []byte
)

func file_proxy_satls_config_proto_rawDescGZIP() []byte {
	file_proxy_satls_config_proto_rawDescOnce.Do(func() {
		file_proxy_satls_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_satls_config_proto_rawDesc), len(file_proxy_satls_config_proto_rawDesc)))
	})
	return file_proxy_satls_config_proto_rawDescData
}

var file_proxy_satls_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_satls_config_proto_goTypes = []any{
	(*Account)(nil),       // 0: v2node.proxy.satls.Account
	(*ServerConfig)(nil),  // 1: v2node.proxy.satls.ServerConfig
	(*protocol.User)(nil), // 2: xray.common.protocol.User
}
var file_proxy_satls_config_proto_depIdxs = []int32{
	2, // 0: v2node.proxy.satls.ServerConfig.users:type_name -> xray.common.protocol.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_satls_config_proto_init() }
func file_proxy_satls_config_proto_init() {
	if File_proxy_satls_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_satls_config_proto_rawDesc), len(file_proxy_satls_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_satls_config_proto_goTypes,
		DependencyIndexes: file_proxy_satls_config_proto_depIdxs,
		MessageInfos:      file_proxy_satls_config_proto_msgTypes,
	}.Build()
	File_proxy_satls_config_proto = out.File
	file_proxy_satls_config_proto_goTypes = nil
	file_proxy_satls_config_proto_depIdxs = nil
}
